(ns nef.nes.ce.neural-network-test
  (:use clojure.test)
  (:require [nef.nes.ce [neural-network :as nn]
             [cellular-encoding-j :as ce]]))



(deftest cellular-encoding-generated-net
  (testing "XOR function generated by cellular encoding"
    (binding [ce/*lifespan* 1]
      (let [graph (ce/evaluate-tree-grammar '(seq (par (rec) (end))
                                                  (seq (par (incbias (end)) (end))
                                                       (val- (end)))))
            ]
        (is (= [1] (nn/evaluate-ff-net-cell graph [1 0])))
        (is (= [1] (nn/evaluate-ff-net-cell graph [0 1])))
        (is (= [0] (nn/evaluate-ff-net-cell graph [1 1])))
        (is (= [0] (nn/evaluate-ff-net-cell graph [0 0])))
        )))
  (testing "parity function for three inputs generated by cellular encoding"
    (binding [ce/*lifespan* 2]
      (let [graph (ce/evaluate-tree-grammar
                   '(seq (par (rec) (end))
                         (seq (par (incbias (end)) (end))
                              (val- (end)))))
            ]
        (is (= [0] (nn/evaluate-ff-net-cell graph [1 0 1])))
        (is (= [0] (nn/evaluate-ff-net-cell graph [0 1 1])))
        (is (= [1] (nn/evaluate-ff-net-cell graph [1 1 1])))
        (is (= [1] (nn/evaluate-ff-net-cell graph [0 0 1])))
        (is (= [1] (nn/evaluate-ff-net-cell graph [1 0 0])))
        (is (= [1] (nn/evaluate-ff-net-cell graph [0 1 0])))
        (is (= [0] (nn/evaluate-ff-net-cell graph [1 1 0])))
        (is (= [0] (nn/evaluate-ff-net-cell graph [0 0 0])))))))


